In [1]:
# tensor manupulation
# .reshaping
# .slicing
# .joining or spitting
# .transposing and permuatation
# .transposing and permuting dimension

# tensor manupulation
# .reshaping
# .slicing
# .joining or spitting
# .transposing and permuatation
# .transposing and permuting dimension

In [2]:
# reshaping tensors
#reshape'
# view
import torch

In [3]:
original_tensor=torch.arange(12)
print(original_tensor)
print(original_tensor.nelement())
print(original_tensor.ndim)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
12
1


In [4]:
reshape_tensor=original_tensor.reshape(2,6)
print(reshape_tensor)
print(reshape_tensor.ndim)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
2


In [5]:
flattened_tensor=original_tensor.view(-1)
print(flattened_tensor)
print(flattened_tensor.ndim)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
1


## sliccing

In [8]:
tensor_a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor_a)
print(tensor_a.ndim)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2


In [9]:
print(tensor_a[0])

tensor([1, 2, 3])


In [10]:
print(tensor_a.shape)

torch.Size([3, 3])


In [11]:
sub_tensor=(tensor_a[1:,1:])
print(sub_tensor)

tensor([[5, 6],
        [8, 9]])


## Joining tensor

In [12]:
# torch concatenation-> it means merge of two rows and column
tensor1=torch.tensor([[1,2],[3,4]])
tensor2=torch.tensor([[3,4],[5,6]])

concat_tensor_rows=torch.cat((tensor1,tensor2),dim=0)
concat_tensor_columns=torch.cat((tensor1,tensor2),dim=1)

print(tensor1)
print(tensor2)
print(concat_tensor_rows)
print(concat_tensor_columns)

tensor([[1, 2],
        [3, 4]])
tensor([[3, 4],
        [5, 6]])
tensor([[1, 2],
        [3, 4],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4],
        [3, 4, 5, 6]])


# splitting tensor


*torch_chunks()->=divides into equal sides chunks
*chunks=torch.chunk(original_tensor,3,dim=0)

In [18]:

original_tensor=torch.arange(12)
print(original_tensor)
chunks=torch.chunk(original_tensor,4,dim=0)
print(chunks)
for chunks in chunks:
  print(chunks)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10, 11]))
tensor([0, 1, 2])
tensor([3, 4, 5])
tensor([6, 7, 8])
tensor([ 9, 10, 11])


In [21]:
splits=torch.split(original_tensor,4,dim=0)
print(splits)
for splits in splits:
  print(splits)

(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10, 11]))
tensor([0, 1, 2, 3])
tensor([4, 5, 6, 7])
tensor([ 8,  9, 10, 11])


# transposing and premuting
permuat()-->rearranges all dimensions in the specified order


--transposing()-->swaps two dimension,mxn-->nxm

In [24]:
tensor_original=torch.arange(24).reshape(12,2)

transposed_tensor=tensor_original.transpose(0,1)
print(tensor_original)
print(tensor_original.shape)
print(transposed_tensor)
print(transposed_tensor.shape)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])
torch.Size([12, 2])
tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])
torch.Size([2, 12])


In [29]:
tensor_original=torch.arange(24).reshape(2,3,4) #2 tensor of 3 rows and 4 column
print(2*3*4)
print(tensor_original)
print(tensor_original.shape)
permute_tensor=tensor_original.permute(2,0,1) # HERE [2,0,1] FOR permute the tensor
print(permute_tensor)
print(permute_tensor.shape)

24
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]]])
torch.Size([4, 2, 3])


# detaching and cloning